### ISSUE TITLE
Root-level imports cause app failures if not building with mastarm

### ISSUE THREAD

**Issue by landonreed** [conveyal/mastarm#142]
If not building an application with `mastarm` (e.g., `webpack`), the application fails on some auth0 code because `process.env` is undefined.

**My proposed solution:**

1.  Because root-level imports can actually lead to a lot of unused imports, we should add warnings to the console`index.js` whenever these imports are used, with a suggestion on how the import should be written (e.g., `root-level imports cause application bloat and may produce undesired results!`).
2.  Fix auth0 code (and any other components) to check for process.env before assigning the variables.
3.  There may in fact be other cases where imports from `woonerf` cause failure outside of `mastarm`, so we should check those, too.

cc @trevorgerhardt

**Comment by evansiroky** [comment]
This library should definitely not fail if an environment variable is not set.  That's not even specific to mastarm.  I'll work on a fix for that today.

**Comment by evansiroky** [comment]
Wait a minute, this is the mastarm library that this issue is reproted in.  @landonreed, I'm going to move this issue over to woonerf.  Please reopen if you find a mastarm-specific bug.

**Comment by landonreed** [comment]
Good grief.  My mistake.

**Comment by evansiroky** [comment]
@landonreed I made some simple test cases and was unable to reproduce a failure in loading the [woonerf](https://github.com/conveyal/woonerf) library.  Furthermore, I also looked through the code and didn't see anything that might cause a run-time error from being imported.  Please submit a PR with a failing test case in [woonerf](https://github.com/conveyal/woonerf) to show how this error can be reproduced.
