### ISSUE TITLE
Test runner?

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/mastarm#20]
Add a test runner for front-end tests. Need to do some research on which one to use first.

**Comment by trevorgerhardt** [comment]
Check out
- http://airbnb.io/enzyme/
- https://github.com/avajs/ava
- https://facebook.github.io/react/docs/test-utils.html

**Comment by trevorgerhardt** [comment]
Jest?

**Comment by evansiroky** [comment]
Fixed by #33
