### ISSUE TITLE
Run tests before deployment and abort if failure occurs

### ISSUE THREAD

**Issue by landonreed** [conveyal/mastarm#216]
`mastarm deploy` should by default run tests (`yarn test` for example) before the deployment occurs.  Otherwise, we risk bad code getting into production (for example, if I forget to `git stash` some changes, we could be in for a wild ride).

@mattwigway suggests that an override should be provided and I agree.  Perhaps we just add a `--force` option that still runs `yarn test`, but a failure does not cause abort.

**Comment by trevorgerhardt** [comment]
This can be done with a `"predeploy": "yarn test"` addition to scripts in package.json.
