### ISSUE TITLE
Mastarm script error

### ISSUE THREAD

**Issue by bobporcaro** [conveyal/mastarm#224]
Hi,

I'm trying to install Convyal with this tutorial: 
**http://conveyal-data-tools.readthedocs.io/en/dev/dev/deployment/**

I'm blocked at step "Building and Running the Application", more precisely when I try to run:
`npm run deploy -- s3://$S3_BUCKET_NAME/dist
`

The issue seems to be a syntax error from mastarm-build script. Please see logs below:

```
/usr/local/lib/node_modules/mastarm/bin/mastarm-build:31
  [...commander.args, ...(get('entries') || [])],
   ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

Could you help me ?

Thx

**Comment by evansiroky** [comment]
What version of node.js are you using?

**Comment by bobporcaro** [comment]
v4.2.6

And I see that we need v6 to use mastarm... sorry, I'm not used to node :)

I'm gonna try with an updated node.

**Comment by bobporcaro** [comment]
I've updated node to v8.6.0 and I had this error:

`events.js:182
      throw er; // Unhandled 'error' event
      ^

SyntaxError: Unexpected token (1:0) while parsing file: /home/boris/Documents/Conveyal/datatools-ui/node_modules/auth0-lock/lib/html/main.ejs
    at Parser.pp$4.raise (/home/boris/Documents/Conveyal/datatools-ui/node_modules/acorn/dist/acorn.js:2610:13)
    at Parser.pp.unexpected (/home/boris/Documents/Conveyal/datatools-ui/node_modules/acorn/dist/acorn.js:637:8)
    at Parser.pp$3.parseExprAtom (/home/boris/Documents/Conveyal/datatools-ui/node_modules/acorn/dist/acorn.js:2094:10)
    at Parser.pp$3.parseExprSubscripts (/home/boris/Documents/Conveyal/datatools-ui/node_modules/acorn/dist/acorn.js:1955:19)
    at Parser.pp$3.parseMaybeUnary (/home/boris/Documents/Conveyal/datatools-ui/node_modules/acorn/dist/acorn.js:1932:17)
    at Parser.pp$3.parseExprOps (/home/boris/Documents/Conveyal/datatools-ui/node_modules/acorn/dist/acorn.js:1874:19)
    at Parser.pp$3.parseMaybeConditional (/home/boris/Documents/Conveyal/datatools-ui/node_modules/acorn/dist/acorn.js:1857:19)
    at Parser.pp$3.parseMaybeAssign (/home/boris/Documents/Conveyal/datatools-ui/node_modules/acorn/dist/acorn.js:1832:19)
    at Parser.pp$3.parseExpression (/home/boris/Documents/Conveyal/datatools-ui/node_modules/acorn/dist/acorn.js:1803:19)
    at Parser.pp$1.parseStatement (/home/boris/Documents/Conveyal/datatools-ui/node_modules/acorn/dist/acorn.js:797:45)`

Do I need to downgrade nodejs to v6 ?

**Comment by evansiroky** [comment]
Yes, please downgrade to node 6.  Mastarm doesn't support node 8 yet.

**Comment by bobporcaro** [comment]
Hi,

My configuration seems to be good now: npm v3 and node v6.

Now I'm blocked by s3 I think:

`updated css file: dist/index.css
WARN: Output exceeds 32000 characters
upload failed: dist/index.js.map to s3://localhost/dist/index.js.map An error occurred (InvalidRequest) when calling the CreateMultipartUpload operation: Missing required header for this request: x-amz-content-sha256
upload failed: dist/index.css to s3://localhost/dist/index.css ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
upload failed: dist/index.js to s3://localhost/dist/index.js ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
upload failed: dist/index.css.map to s3://localhost/dist/index.css.map ('Connection aborted.', timeout('The write operation timed out',))

npm ERR! Linux 4.4.0-96-generic
npm ERR! argv "/home/boris/.nvm/versions/node/v6.11.3/bin/node" "/home/boris/.nvm/versions/node/v6.11.3/bin/npm" "run" "deploy" "--" "s3://localhost/dist"
npm ERR! node v6.11.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! datatools-manager@0.0.0-development deploy: `mastarm build --minify --env production && aws s3 cp --recursive --acl public-read dist "s3://localhost/dist"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the datatools-manager@0.0.0-development deploy script 'mastarm build --minify --env production && aws s3 cp --recursive --acl public-read dist "s3://localhost/dist"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the datatools-manager package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mastarm build --minify --env production && aws s3 cp --recursive --acl public-read dist "s3://localhost/dist"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs datatools-manager
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls datatools-manager
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/boris/Documents/Conveyal/datatools-ui/npm-debug.log`

I've even created an AWS account to get "Access key ID" (necessary for a previous issue)... I don't know if I'm on a good way...

If you have any advice about configuration, I am of course interested.

**Comment by bobporcaro** [comment]
Actually, I don't understand why we have to use AWS to build the application.

Do I have to create myself a bucket on AWS ?

**Comment by trevorgerhardt** [comment]
The `mastarm deploy` command is specifically for deploying to AWS.

**Comment by bobporcaro** [comment]
Ok, thanks for your answers. Is it necessary to deploy the app to AWS ? 

Actually, I'd like to test Conveyall locally but I have to admit that I'm blocked by configuration....

**Comment by trevorgerhardt** [comment]
No. You can run the app locally. See the development guide for Data Tools: http://conveyal-data-tools.readthedocs.io/en/latest/dev/development/
