### ISSUE TITLE
Remove --watch

### ISSUE THREAD

**Issue by trevorgerhardt** [conveyal/mastarm#250]
We don't use `--watch` while developing Taui or Analysis UI. If that's not used in any other projects then we might as well remove the flag and it's corresponding paths.

**Comment by evansiroky** [comment]
Looks like commute still uses `--watch`: https://github.com/conveyal/commute/blob/dev/package.json.  But if there are other ways to do this, I guess it's fine to remove the functionality.

**Comment by trevorgerhardt** [comment]
Ah. Forgot about that one. Hmmm ok.

Commute would be an interesting project to port over to Now/Next.js: https://nextjs.org/
