### ISSUE TITLE
Add jsx-a11y to linting

### ISSUE THREAD

**Issue by landonreed** [conveyal/mastarm#288]
@evansiroky, there is a requirement for a potential trip planning customer to adhere to [WCAG 2.1](https://www.w3.org/TR/WCAG21/). Given this, I think it would be helpful to add `jsx-a11y` to the lint rules, or at least somehow enable this for certain projects like otp-rr.

I did see this brought up [in this issue](https://github.com/conveyal/mastarm/issues/109). Do you have any objections to adding this to the linter?

**Comment by evansiroky** [comment]
No objections.
